export default [
  { value: "agric", name: "AGRICULTURAL SCIENCE" },
  { value: "", name: "ANIMAL HUSBANDRY" },
  { value: "", name: "BASIC SCIENCE & TECHNOLOGY" },
  { value: "", name: "BIOLOGY" },
  { value: "", name: "BUSINESS MANAGEMENT" },
  { value: "", name: "BUSINESS STUDIES" },
  { value: "", name: "CATERING CRAFT PRACTICE" },
  { value: "", name: "CHEMISTRY" },
  { value: "", name: "CHRISTIAN RELIGIOUS STUDIES" },
  { value: "", name: "CIVIC EDUCATION" },
  { value: "", name: "COMMERCE" },
  { value: "", name: "COMPUTER STUDIES" },
  { value: "", name: "ECONOMICS" },
  { value: "", name: "ENGLISH LANGUAGE" },
  { value: "", name: "FINANCIAL ACCOUNTING" },
  { value: "", name: "FRENCH" },
  { value: "", name: "FURTHER MATHEMATICS" },
  { value: "", name: "GENERAL AGRICULTURE" },
  { value: "", name: "GENERAL MATHEMATICS OR MATHEMATICS (CORE)" },
  { value: "", name: "GEOGRAPHY" },
  { value: "", name: "INTEGRATED SCIENCE" },
  { value: "", name: "ISLAMIC RELIGIOUS STUDIES" },
  { value: "", name: "LITERATURE IN ENGLISH" },
  { value: "", name: "PHYSICS" },
  { value: "", name: "SOCIAL STUDIES" },
  { value: "", name: "TECHNICAL DRAWING" },
  { value: "", name: "VISUAL ART" },
  { value: "", name: "WOODWORK" },
  { value: "", name: "YORUBA" }
];
